app:
  name: "instagram_accounts"
strings:
  en:
    help : |
      Here are some commands you can use:
      - /menu: Show the main menu
      - /admin: Show the admin menu
      - /start: Start the bot
  ru:
    help : |

      ℹ️ Я помогу тебе найти трендовые идеи для Reels и постов.

      Что я умею:
      - Мониторить аккаунты Instagram
      - Выявлять быстрорастущие посты
      - Присылать ссылки и метрики

      Для начала — добавь аккаунты и выбери тематику!

      📞 Поддержка: @your_support