strings:
  enter_nickname:
    ru: "Отправь никнейм аккаунта, который хочешь проанализировать"
  enter_number_of_videos:
    ru: "Введите топ N популярных видео:"
  received:
    ru: Ищу аккаунт...🔎
  no_found:
    ru: "Что-то пошло не так, я не нашёл аккаунт. Проверь ник или попробуй ещё раз позже 🤷🏼‍♂️"
  private_account:
    ru: "Кажется, этот аккаунт закрыт или никнейм введён неверно. Пожалуйста, проверь его и попробуй снова."
  error:
    ru: "Ошибка."
  ask_number_videos:
    ru: "Отлично, я нашёл этот аккаунт! Выбери количество видео, которые ты хочешь увидеть"
  result_ready:
    ru: |
      <b>Самые популярные рилс в аккаунте @{nickname}</b>
      <i>Проанализировано 100 последних видео</i>
  results:
    ru: |
      {idx}. {link}
      👁 <b>{views} просмотров</b>
      ❤️<b>{likes} лайков</b> — {likes_comparative}
      💬 <b>{comments} комментариев</b> — {comments_comparative}
  comparative_more:
    ru: "<i>на {value} больше чем обычно.</i>"
  comparative_less:
    ru: "<i>на {value} меньше чем обычно.</i>"
  final_message:
    ru: "<b>Просмотры и подписчики — легко с @{bot_name}</b> ❤️"
  download_report:
    ru: "Скачать отчёт"
  advice_message:
    ru: |
      <b>Советы по анализу аккаунтов</b>

      1️⃣ <b>Анализируйте чужие аккаунты — ищите другие блоги в вашей и смежных нишах:</b>

      — Посмотрите, какие форматы и темы работают у ваших коллег, и используйте их для вдохновения
      — Посмотрите лучшие видео и подумайте, что добавить в свои ролики, чтобы привлечь больше зрителей

      2️⃣ <b>Анализируйте свой аккаунт:</b>
      — Определите, какой контент нравится вашей аудитории или имеет потенциал набрать просмотры в рекомендациях

      — Выберите ролики, которые можно доработать или повторить, чтобы увеличить их успех

      🔍 <b>Совет:</b> Регулярный анализ поможет вам находить новые идеи и совершенствовать свой контент для больших результатов!