strings:
  ru:
    no_rights: "У вас нет прав администратора для доступа к этому приложению"
    menu:
      title: "Меню администратора"
      options:
        - label: "Экспорт данных"
          value: "export_data"
        - label: "Публичное сообщение"
          value: "public_message"
        - label: "Управление пользователями"
          value: "users"
        - label: "Баланс Hiker API"
          value: "hikerapi_balance"
        - label: "О приложении"
          value: "about"
  en:
    no_rights: "You do not have admin rights to access this application"
    menu:
      title: "Admin menu"
      options:
        - label: "Export data"
          value: "export_data"
        - label: "Public message"
          value: "public_message"
        - label: "User management"
          value: "users"
        - label: "Hiker API Balance"
          value: "hikerapi_balance"
        - label: "About"
          value: "about"
