app:
  name: "instagram_accounts"
  accounts_limit: 100
strings:
  en:
    add_account: "Add Instagram Account"
    remove_account: "Remove Account"
    operation_cancelled: "Operation cancelled"
    my_accounts: "My Accounts"
    back_to_menu: "Back to main menu"
    instagram_accounts_menu: "Instagram Accounts - Choose an action:"
    your_accounts: "Your Instagram accounts to follow:"
    no_accounts: "You don't have any Instagram accounts to follow yet."
    back_to_accounts: "Back to my accounts"
    account_not_found: "Account not found"
    account_details: "*Account Details*\n\nUsername: @{username}\nAdded: {created_at}"

    enter_username: "Enter Instagram username (without @):"
    account_added: "Instagram account(s) {username} was successfully added to your follow list."
    account_removed: "Instagram account was successfully removed from your follow list."

    limit_reached: "You have reached the limit of {limit} Instagram accounts. Please remove an account before adding a new one."

    main_menu: "Main Menu"

    cancel: "Cancel"
  ru:
    add_account: ➕ Добавить аккаунт
    add_another_account: ➕ Добавить другой аккаунт
    remove_account: "🗑️ Удалить аккаунт"
    operation_cancelled: "Операция отменена"
    my_accounts: 📜 Мои аккаунты
    list_my_accounts: "📜 Список моих аккаунтов"
    back_to_menu: "Вернуться в главное меню"
    instagram_accounts_menu: "Выберите действие:"
    your_accounts: "📜 Ты сейчас отслеживаешь:"
    no_accounts: "У тебя пока нет аккаунтов для отслеживания."
    back_to_accounts: "Вернуться к моим подпискам"
    account_not_found: "Аккаунт не найден"
    account_details: "*Детали аккаунта*\n\nИмя пользователя: @{username}\nДобавлено: {created_at}"

    enter_username: ✍️ Введите имя аккаунта или ссылку на него в Instagram. Ты можешь указать несколько аккаунтов, разделяя их новой строкой.
    account_added_confirmation: "✅ Аккаунт успешно добавлен! @{username} добавлен в список для отслеживания."
    account_added: "✅ Аккаунт(ы) успешно добавлен(ы)! {username} добавлен(ы) в список для отслеживания."
    account_removed: "Instagram аккаунт был успешно удален из списка для отслеживания."

    limit_reached: "🚫 Ты достиг лимита в {limit} Instagram аккаунтов. Пожалуйста, удали один из них перед добавлением нового."

    main_menu: "Главное меню"

    cancel: "Отмена"

    notification:
      title: "🚀 Новые потенциальные тренды для тебя!"
      no_new_trends: "Нет новых трендов на данный момент."
      template: |
        📌 @{account_name}
        🔗 [Смотреть ролик]({video_url})
        📝 Почему выбран: {reason}
        📊 Показатели:
        - Просмотры: {views}
        - Лайки: {likes}
        - Комментарии: {comments}
        - Подписчики: {followers}
        🌟 Оценка трендовости: {trend_category}

